---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 提供了几项新功能和增强功能。 
---
= Cloud Volumes ONTAP 9.10.0 中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 提供了几项新功能和增强功能。

最新版本的BlueXP还引入了其他功能和增强功能。请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["《BlueXP发行说明》"^] 了解详细信息。



== 不再支持c4、m4和r4实例(2022年10月28日)

在AWS中、Cloud Volumes ONTAP 不再支持C4、M4和M4 EC2实例类型。如果现有系统运行的是C4、M4或r4实例类型、则必须更改为c5、M5或R5实例系列中的实例类型。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["了解如何更改Cloud Volumes ONTAP 的EC2实例类型"^]。

请参见 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 支持"^] 了解有关这些实例类型的可用性和支持终止的更多信息。



== 9.10.0 GA （ 2021 年 10 月 4 日）

9.10.0 GA 版本可在 AWS ， Azure 和 Google Cloud 中使用。此版本包含以下新增功能和增强功能：



=== 提高写入性能

启用高写入速度后，我们提高了 Cloud Volumes ONTAP 写入性能。



=== 增加了 Azure 中的 NVRAM 磁盘大小

对于 Azure 中的新 Cloud Volumes ONTAP 系统， NVRAM 磁盘大小已从 128 GiB 增加到 512 GiB 。


NOTE: 如果您选择的是单节点系统，并且虚拟机支持超 SSD ，则系统将使用 32 GiB 超 SSD 进行 NVRAM ，而不是 512 GiB 高级 SSD 。



== 所需版本的BlueXP Connector

要部署新的Cloud Volumes ONTAP 9.10.0系统并将现有系统升级到9.10.0、BlueXP Connector必须运行版本3.9.11或更高版本。



== 升级说明

* 必须从BlueXP完成Cloud Volumes ONTAP 升级。您不应使用 System Manager 或命令行界面升级 Cloud Volumes ONTAP 。这样做可能会影响系统稳定性。
* 您可以从 9.9.1 版升级到 Cloud Volumes ONTAP 9.10.0 。BlueXP将提示您将现有Cloud Volumes ONTAP 9.9.1系统升级到9.10.0版本。
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["了解在收到BlueXP通知时如何升级"^]。

* 升级单节点系统会使系统脱机长达 25 分钟，在此期间 I/O 会中断。
* 升级 HA 对无中断， I/O 不会中断。在此无中断升级过程中，每个节点会同时进行升级，以继续为客户端提供 I/O 。




=== DS3_v2

从 9.9.1 版开始，新的和现有的 Cloud Volumes ONTAP 系统不再支持 DS3_v2 VM 类型。如果您的现有系统在此 VM 类型上运行，则需要在升级到 9.10.0 之前更改 VM 类型。
